### ISSUE TITLE
application

### ISSUE THREAD

**Issue by Husheng616** [BIueMan/L515_camera#1]
Hi，I am a master student from Sweden. My thesis project is about 3d printer and defect detection. We have a L515_ camera and require to reconstruct the object. I wanna ask is it possible to reconstruct it if the camera position is fixed?

**Comment by BIueMan** [comment]
the camera is great for building Depth image if the object is close, so i think it will suit you well on this project.
the best thing you can extract from the camera is a cloud points of the object, and from there you could try and reconstruct the object.
you can use MSE with the real object and the couldpoint , to see how good is the printing i think.

**Comment by tonglily** [comment]
Hi，I am a master student from china.I want to know how to perform depth calibration on l515
